import os

SLACK_CHANNEL_ID_INCOMING = os.environ["SLACK_CHANNEL_ID_INCOMING"]
SLACK_CHANNEL_ID_OUTGOING = os.environ["SLACK_CHANNEL_ID_OUTGOING"]
SLACK_USER_ID_BOT = os.environ["SLACK_USER_ID_BOT"]
SLACK_USER_ID_MESSENGER = os.environ["SLACK_USER_ID_MESSENGER"]
WIKI_BASE = os.environ["WIKI_BASE"]
WIKI_REMOTE_PRODUCTION = os.environ["WIKI_REMOTE_PRODUCTION"]
WIKI_REMOTE_STAGING = os.environ["WIKI_REMOTE_STAGING"]
