# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Share an update
on:
  push:
    branches: [main]
jobs:
  upgrade:
    name: Suggest the latest changes
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Send a message to channel
        id: message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            text: "chore(<!channel>): merge w the latest changes on main"
      - name: Respond with affection
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: reactions.add
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            timestamp: "${{ steps.message.outputs.ts }}"
            name: heart
