# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Share an update
on:
  push:
    branches: [main]
jobs:
  upgrade:
    name: Suggest the latest changes
    runs-on: self-hosted
    permissions:
      contents: none
    steps:
      - name: Send a message to channel
        id: message
        uses: zimeg/slack-github-action@v3.0.6-rc.1
        with:
          method: chat.postMessage
          proxy: "http://127.0.0.1:3128"
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            text: "chore(<!channel>): merge w the latest changes on main"
      - name: Respond with affection
        if: ${{ steps.message.outputs.ok }}
        uses: zimeg/slack-github-action@v3.0.6-rc.1
        with:
          method: reactions.add
          proxy: "http://127.0.0.1:3128"
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            timestamp: "${{ steps.message.outputs.ts }}"
            name: heart
