# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  push:
jobs:
  test:
    name: Attempt sends
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Checkout this repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: RC with YAML
        if: ${{ always() }}
        uses: zimeg/slack-github-action@91855720aaee2e23bf81dae3512204a371ca1609 # v2.1.1-rc.1
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            text: "${{ github.event.head_commit.message }}"

      - name: RC with YAML (files.uploadV2)
        if: ${{ always() }}
        uses: zimeg/slack-github-action@91855720aaee2e23bf81dae3512204a371ca1609 # v2.1.1-rc.1
        env:
          CHANNEL_ID: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload-file-path: ./uploads.yml
          payload-templated: true

      - name: RC with JSON
        if: ${{ always() }}
        uses: zimeg/slack-github-action@91855720aaee2e23bf81dae3512204a371ca1609 # v2.1.1-rc.1
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}",
              "text": "${{ github.event.head_commit.message }}"
            }

      - name: RC with JSON (files.uploadV2)
        if: ${{ always() }}
        uses: zimeg/slack-github-action@91855720aaee2e23bf81dae3512204a371ca1609 # v2.1.1-rc.1
        env:
          CHANNEL_ID: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload-file-path: ./uploads.json
          payload-templated: true

      - name: Latest with YAML
        if: ${{ always() }}
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
            text: "${{ github.event.head_commit.message }}"

      - name: Latest with YAML (files.uploadV2)
        if: ${{ always() }}
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        env:
          CHANNEL_ID: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload-file-path: ./uploads.yml
          payload-templated: true

      - name: Latest with JSON
        if: ${{ always() }}
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}",
              "text": "${{ github.event.head_commit.message }}"
            }

      - name: Latest with JSON (files.uploadV2)
        if: ${{ always() }}
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        env:
          CHANNEL_ID: ${{ secrets.SLACK_GITHUB_ACTION_CHANNEL_ID }}
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_GITHUB_ACTION_BOT_TOKEN }}
          payload-file-path: ./uploads.json
          payload-templated: true
